[source.crates-io]
replace-with = "vendored-sources"

[source."git+https://github.com/byte-sourcerer/datafusion-sqlparser-rs?rev=1cd4f7c"]
git = "https://github.com/byte-sourcerer/datafusion-sqlparser-rs"
rev = "1cd4f7c"
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
